### ISSUE TITLE
Bluetooth not working due to pydantic 2.*

### ISSUE THREAD

**Issue by rydia001** [mukai1011/pokecon-extensions#1]
`pip install pokecon-extentions` で最新をインストールすると以下のようにテストで落ちます。
原因はpydantic 2.0系が濃厚で、`pip install "pydantic==1.*" --force-reinstall` で解決したので共有しておきます。 

python converter.py
```
Traceback (most recent call last):
  File "converter.py", line 6, in <module>
    from pokecon_extensions.bluetooth import Config, from_virtual_serial
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pokecon_extensions\bluetooth\__init__.py", line 1, in <module>
    from .adapter import Adapter
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pokecon_extensions\bluetooth\adapter.py", line 5, in <module>
    from .session import Session
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pokecon_extensions\bluetooth\session.py", line 10, in <module>
    from .state import State
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pokecon_extensions\bluetooth\state.py", line 130, in <module>
    class State(BaseModel):
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pokecon_extensions\bluetooth\state.py", line 133, in State
    l=Stick(changed=True, x=128, y=128), r=Stick(changed=True, x=128, y=128))
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\main.py", line 142, in __init__
    self.__setstate__(self._process_values(data))
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\main.py", line 312, in _process_values
    return validate_model(self, input_data)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\main.py", line 451, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=model.__class__)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\fields.py", line 234, in validate
    v, errors = self._validate_singleton(v, values, loc, cls)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\fields.py", line 330, in _validate_singleton
    value, error = field.validate(v, values, loc=loc, cls=cls)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\fields.py", line 234, in validate
    v, errors = self._validate_singleton(v, values, loc, cls)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\fields.py", line 337, in _validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\fields.py", line 343, in _apply_validators
    v = validator(v)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\main.py", line 309, in validate
    return cls(**value)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\main.py", line 142, in __init__
    self.__setstate__(self._process_values(data))
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\main.py", line 312, in _process_values
    return validate_model(self, input_data)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\main.py", line 451, in validate_model
    v_, errors_ = field.validate(value, values, loc=field.alias, cls=model.__class__)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\fields.py", line 234, in validate
    v, errors = self._validate_singleton(v, values, loc, cls)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\fields.py", line 337, in _validate_singleton
    return self._apply_validators(v, values, loc, cls, self.validators)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pydantic\fields.py", line 347, in _apply_validators
    v = validator(cls, v)
  File "C:\Users\forse\miniconda3\envs\PokeCon3_7\lib\site-packages\pokecon_extensions\bluetooth\state.py", line 84, in x_axis_must_be_between_0_255
    assert 0x0 <= axis and axis <= 0xff
AssertionError
```

**Comment by u1f992** [comment]
ご報告いただいたにもかかわらず長い間放置してしまいすみません。最近Poke-Controllerを触っていないので勝手を忘れており、Pull requestを作成していただけますと助かります。
